import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — PlainDocs" },
      {
        name: "description",
        content:
          "How PlainDocs collects, uses, and stores your information.",
      },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        PlainDocs · plaindocs.techbees.me · Effective: June 2026
      </p>

      <div className="mt-8 space-y-6 text-foreground leading-relaxed">
        <p>
          PlainDocs is a tool that explains documents in plain language. This
          Privacy Policy explains what information we collect when you use
          PlainDocs, how we use it, and what choices you have.
        </p>
        <p>
          Plain English, no legal runaround. If something here is unclear,
          use the{" "}
          <a href="https://tally.so/r/ODEQE7" target="_blank" rel="noopener noreferrer" className="text-teal hover:underline">help form</a>{" "}or email{" "}
          <a href="mailto:support@techbees.me" className="text-teal hover:underline">support@techbees.me</a>.
        </p>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">
            1. What We Collect
          </h2>

          <h3 className="text-base font-semibold">Account Information</h3>
          <p>
            When you create an account, we collect your email address and a
            password (stored securely via Amazon Cognito). This is the only
            personal information required to use PlainDocs.
          </p>

          <h3 className="text-base font-semibold">Document Summaries</h3>
          <p>
            When you submit a document for explanation, PlainDocs sends the
            content to an AI model (Amazon Nova Lite via Amazon Bedrock) to
            generate a plain-language summary. We store:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>The summary/explanation generated by the AI</li>
            <li>
              The title of the document (generated by the AI, not taken from
              your file)
            </li>
            <li>The detected language of your input</li>
            <li>Whether you marked the document as Private or Standard</li>
            <li>A timestamp</li>
          </ul>
          <p>
            We do not store the original document you submitted. Once the
            summary is generated, the source document is discarded. The summary
            and its metadata are stored in your History.
          </p>

          <h3 className="text-base font-semibold">Usage Data</h3>
          <p>
            Standard web logs may record your IP address, browser type, and the
            pages you visit. This is handled at the infrastructure level (AWS)
            and is not used to build profiles or for marketing.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">
            2. How We Use Your Information
          </h2>
          <p>We use the information we collect to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              Provide the PlainDocs service (generate and store document
              explanations)
            </li>
            <li>Maintain your History of past explanations</li>
            <li>Keep your account secure</li>
            <li>Respond to help requests you initiate</li>
          </ul>
          <p>
            We do not sell your data. We do not use your documents to train AI
            models. We do not send marketing emails.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">
            3. How Your Data Is Stored
          </h2>
          <p>PlainDocs is built on Amazon Web Services (AWS):</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Account credentials are managed by Amazon Cognito</li>
            <li>
              Document summaries and history are stored in Amazon DynamoDB
            </li>
            <li>AI processing is handled by Amazon Bedrock (Nova Lite)</li>
            <li>The frontend is hosted on Lovable</li>
          </ul>
          <p>
            All AWS services used by PlainDocs are operated in AWS
            infrastructure. Your data does not leave the AWS environment during
            processing.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">
            4. Private Mode
          </h2>
          <p>
            PlainDocs offers a Private Doc Mode. When you mark a document as
            private:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>The explanation is stored with a private flag in your history</li>
            <li>It is not accessible via the Share feature</li>
            <li>It is only visible when you are logged in to your account</li>
          </ul>
          <p>
            <span className="font-semibold">Important:</span> Private mode
            controls visibility within PlainDocs. The document content is
            processed through the same AI infrastructure as Standard mode. If
            you are working with highly sensitive documents (legal, medical,
            financial), please review whether any cloud-based processing is
            appropriate for your situation.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">5. Sharing</h2>
          <p>
            PlainDocs includes a Share feature for Standard mode documents.
            Sharing creates a URL that encodes the document summary. Anyone
            with the link can view that summary. Private mode documents cannot
            be shared.
          </p>
          <p>
            You control whether to share. We do not share your documents on
            your behalf.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">
            6. Data Retention
          </h2>
          <p>
            Your document history is retained as long as your account is
            active. If you would like your data deleted, use the{" "}
            <a href="https://tally.so/r/ODEQE7" target="_blank" rel="noopener noreferrer" className="text-teal hover:underline">help form</a> or email{" "}
            <a href="mailto:support@techbees.me" className="text-teal hover:underline">support@techbees.me</a> and we will remove it manually. We are working toward
            adding self-serve account deletion.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">
            7. Third-Party Services
          </h2>
          <p>PlainDocs uses the following third-party services:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              Amazon Web Services (AWS) — cloud infrastructure, AI processing,
              authentication, storage
            </li>
            <li>Lovable — frontend hosting</li>
            <li>Tally — help form submissions</li>
          </ul>
          <p>
            Each of these services has its own privacy policy. Tally form
            submissions go to Tally's servers, not to AWS.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">8. Children</h2>
          <p>
            PlainDocs is not directed at children under 13. We do not knowingly
            collect information from children under 13. If you believe a child
            has submitted information, please contact us and we will remove it.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">
            9. Changes to This Policy
          </h2>
          <p>
            If we make material changes to this policy, we will update the
            effective date at the top of this page. Continued use of PlainDocs
            after changes constitutes acceptance of the updated policy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">10. Contact</h2>
          <p>
            Questions about this policy? Use the{" "}
            <a href="https://tally.so/r/ODEQE7" target="_blank" rel="noopener noreferrer" className="text-teal hover:underline">help form</a> or email{" "}
            <a href="mailto:support@techbees.me" className="text-teal hover:underline">support@techbees.me</a>.
          </p>
        </section>
      </div>
    </main>
  );
}
